apiVersion: v1
kind: Service
metadata:
  name: my-postgres-service
  namespace: default # We're deploying to Docker's local Kubernetes cluster, so the only namespace is "default"
spec:
  type: NodePort
  selector:
    app: my-postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001